mysql:
  image: mysql:latest
  environment:
    MYSQL_USER: mysql
    MYSQL_PASSWORD: password
postgres:
  image: postgres
redis:
  image: redis
memcache:
  image: tutum/memcached
app:
  build: .
  links:
    - postgres
    - mysql
    - redis
    - memcache
  environment:
    PGHOST: postgres
    PGUSER: postgres
    MYSQL_HOST: mysql
    MYSQL_USER: mysql
    MYSQL_PASSWORD: password
    REDIS_URL: redis://redis
    MEMCACHE_SERVERS: memcache
    DATABASE_ADAPTER:
