<% if ENV['DATABASE_ADAPTER'] == 'mysql' %>
development:
  adapter: mysql2
  database: rails_example_development
  user: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: rails_example_test
  user: root
  password:
  host: localhost
<% else %>
development:
  adapter: postgresql
  encoding: unicode
  database: rails_example_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_example_test
  pool: 5
  username: postgres
  password:
<% end %>
