<% if ENV['DATABASE_ADAPTER'] == 'mysql' %>
development:
  adapter: mysql2
  database: rails_example_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: rails_example_test
  username: <%= ENV['MYSQL_USER'] || "root" %>
  password: <%= ENV['MYSQL_ENV_MYSQL_ROOT_PASSWORD'] || "" %>
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] || "localhost" %>
  port: <%= ENV['MYSQL_PORT_3306_TCP_PORT'] || "3306" %>
<% else %>
development:
  adapter: postgresql
  encoding: unicode
  database: rails_example_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_example_test
  pool: 5
  username: postgres
  password:
<% end %>
