#!/bin/bash
set -e

env | grep MYSQL

echo '--- :bundler: Bundling'
bundle

echo "--- :$DATABASE_ADAPTER: Preparing database"
./bin/rake db:create
./bin/rake db:schema:load

echo '--- :rspec: Running specs'
./bin/rspec
